//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourMe.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moderator
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ContactInfo { get; set; }
        public int RoleId { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual UserLogin UserLogin { get; set; }
    }
}
